// WalkingView.swift
// The active-tour screen — the heart of the app.
//
// Mockup: design/mockups.html → .walking view.
//
// What's wired to real backends:
//   • Mic button (lime, primary): hold-to-speak. On press → SpeechRecognizer
//     starts. On release → Gemma streams a response (replaces the lyric
//     center text), then Kokoro speaks it aloud. Identical to the existing
//     DebugView flow.
//   • Photo capture stays visual-only — Phase 3 (MLXVLM Gemma 4
//     multimodal) lights this up.
//   • The lyric narration auto-cycles through static sentences for the
//     current stop. That's mockup data, not generated by Gemma.
//   • GPS-driven stop progression doesn't exist yet — for the demo, "stop"
//     advances on a timer (mirroring the prototype's behavior so we can
//     show the design without GPS hardware).
//
// The bottom mic button uses **press-and-hold** (same gesture as
// DebugView's HoldToSpeakButton), even though the mockup shows
// tap-to-toggle. Hold-to-speak proved to be the more reliable
// interaction during Phase 2 testing.

import SwiftUI

struct WalkingView: View {
    @EnvironmentObject var router: AppRouter
    @EnvironmentObject var gemma: GemmaService
    @EnvironmentObject var tts: ValidationRunner
    @EnvironmentObject var speech: SpeechRecognizer
    @EnvironmentObject var rag: RAGService

    var trail: Trail { router.currentTrail }

    // MARK: - Tour cycle state

    /// Tour state machine. Mirrors `design/mockups.html` — see
    /// `design/README.md` "Tour state machine" section.
    ///   atStop → between → approaching → atStop (next)  … repeat …
    ///   atStop (last stop) → **complete**  (terminal)
    /// The `complete` state replaces the previous wrap-back-to-stop-1
    /// loop and shows the tour summary + "Open journal" CTA.
    enum TourPhase { case atStop, between, approaching, complete }

    @State private var phase: TourPhase = .atStop
    @State private var stopIdx: Int = 0
    @State private var phaseTimer: Timer?
    @State private var isPaused: Bool = false

    // MARK: - Q&A overlay state

    /// True while the user is holding the mic.
    @State private var isHolding: Bool = false
    /// True while we're streaming a Gemma response (after release).
    @State private var isAnswering: Bool = false
    /// Gemma's streaming response text, displayed in place of the lyric.
    @State private var answerText: String = ""

    // MARK: - Modals + UI state

    @State private var showMoreSheet: Bool = false
    @State private var showTourMap: Bool = false
    @State private var showCamera: Bool = false
    @State private var showPhotoContext: Bool = false
    /// The most recently captured photo (Phase 3a). Held in memory only —
    /// dropped when the user dismisses the photo-context strip or ends
    /// the tour. Downscaled to ~1280 px on the long edge inside
    /// CameraController, so memory cost is ~3 MB regardless of how many
    /// captures happen across a session.
    @State private var capturedImage: UIImage? = nil
    @State private var toastMessage: String? = nil
    @State private var toastTask: Task<Void, Never>? = nil

    // MARK: - Narration state (tour-guide TTS)

    /// What kind of speech is currently being routed through Kokoro.
    /// We need to know the difference because they're visually distinct:
    ///   .narration → ambient tour-guide text in the background/lyric area
    ///   .answer    → "Companion" reply in the foreground
    enum SpeechKind { case none, narration, answer }
    @State private var currentlySpeaking: SpeechKind = .none

    /// The full text Kokoro is currently narrating, OR the unspoken remainder
    /// after a previous interruption. Nil = no narration in flight.
    @State private var narrationFullText: String? = nil
    /// Snapshot of `tts.currentCaption` at the moment the user interrupted.
    /// Used to compute the unspoken remainder so we can resume from there.
    @State private var narrationDelivered: String = ""
    /// True between an interrupt-by-question and the resume-after-answer.
    @State private var narrationPaused: Bool = false
    /// The next stop's narration is queued (we'll start it after the
    /// current one finishes naturally). Avoids races with phase timers.
    @State private var pendingNarration: String? = nil

    /// Soft placeholder shown in the lyric area during the 1–2 s window
    /// between a `speakNarration(...)` call and Kokoro's first audio
    /// frame. Without this the user sees an empty lyric area at start,
    /// which feels like the app froze.
    @State private var narrationPreamble: String = ""

    // MARK: - Constants

    /// Phase durations in the demo. Real GPS would replace these.
    private let atStopSeconds:    Double = 9.0
    private let betweenSeconds:   Double = 5.0
    private let approachingSeconds: Double = 3.0

    var body: some View {
        ZStack {
            AppColor.walkingBg.ignoresSafeArea()

            if trail.stops.isEmpty {
                // Defensive empty state: should never happen with the
                // shipped trail catalogue, but if a future trail makes it
                // here without stops, we'd crash on trail.stops[0]. Show
                // a friendly placeholder + an obvious way back to picker.
                emptyTrailFallback
            } else {
                walkingContent
            }
        }
        .onAppear {
            guard !trail.stops.isEmpty else { return }
            startTourCycle()
        }
        .onDisappear {
            stopTourCycle()
            tts.stop()  // halt any in-flight narration when leaving the view
            // Drop the LM's trail/stop framing so a re-entry to picker
            // doesn't carry stale context into the next trail.
            gemma.setActiveContext(trail: nil, stopIdx: nil)
            // Drop the RAG active subject so the next trail starts
            // fresh (no leaked retrieval from a previous tour).
            try? rag.setActiveSubject(nil)
        }
        // When Kokoro stops speaking, decide whether the tour narration
        // ended naturally (good — clear state and resume the phase timer)
        // or was interrupted (handled by interruptNarrationForQuestion).
        .onChange(of: tts.isSpeaking) { _, isSpeaking in
            if !isSpeaking {
                handleSpeakingFinished()
            }
        }
        .animation(.easeInOut(duration: 0.4), value: phase)
        .animation(.easeInOut(duration: 0.35), value: isHolding)
        .animation(.easeInOut(duration: 0.35), value: showPhotoContext)
        .animation(.easeInOut(duration: 0.3), value: toastMessage != nil)
        .animation(.easeInOut(duration: 0.3), value: isPaused)
        .animation(.easeInOut(duration: 0.22), value: showMoreSheet)
        .animation(.easeInOut(duration: 0.3), value: tts.isSpeaking)
        .animation(.easeInOut(duration: 0.3), value: currentlySpeaking)
    }

    private var emptyTrailFallback: some View {
        VStack(spacing: 16) {
            Image(systemName: "leaf")
                .font(.system(size: 32, weight: .light))
                .foregroundStyle(AppColor.lime)
            Text("Trail content coming soon")
                .font(AppFont.sans(20, .semibold))
                .foregroundStyle(AppColor.ink100)
                .tracking(-0.3)
            Text("Stops for \(trail.name) aren't ready yet.")
                .font(AppFont.sans(13, .medium))
                .foregroundStyle(AppColor.ink60)
            Button {
                router.backToPicker()
            } label: {
                Text("Back to trails")
                    .font(AppFont.sans(15, .semibold))
                    .foregroundStyle(AppColor.limeText)
                    .padding(.horizontal, 22)
                    .padding(.vertical, 12)
                    .background(AppColor.lime, in: Capsule())
            }
            .buttonStyle(LimePressStyle())
            .padding(.top, 8)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    @ViewBuilder
    private var walkingContent: some View {
        ZStack {
            // ---- Top: progress bar OR stop hero (atStop) ----
            VStack(spacing: 0) {
                topProgressArea
                Spacer()
            }

            // ---- Center content (lyric / between-info / answer) ----
            centerContent

            // ---- Photo context strip (above center, below progress) ----
            if showPhotoContext {
                VStack {
                    photoContextBar
                        .padding(.horizontal, 16)
                        .padding(.top, 122)
                    Spacer()
                }
                .transition(.move(edge: .top).combined(with: .opacity))
            }

            // ---- Listening overlay (during hold) ----
            if isHolding {
                askTranscriptOverlay
                    .transition(.opacity)
            }

            // ---- Toast ----
            if let msg = toastMessage {
                VStack {
                    Text(msg)
                        .font(AppFont.sans(10.5, .heavy))
                        .tracking(1.6)
                        .textCase(.uppercase)
                        .foregroundStyle(AppColor.lime)
                        .padding(.horizontal, 16)
                        .padding(.vertical, 8)
                        .background(.black.opacity(0.65), in: Capsule())
                        .padding(.top, 130)
                    Spacer()
                }
                .transition(.opacity)
            }

            // ---- Bottom controls ----
            // Hidden in the terminal `.complete` state — the
            // completion card's "Open journal" CTA is the only
            // action; mic / camera / more aren't relevant after the
            // tour ends.
            if phase != .complete {
                VStack {
                    Spacer()
                    bottomControls
                        .padding(.bottom, 60)
                }
            }

            // ---- Paused banner ----
            if isPaused {
                VStack {
                    Spacer()
                    pausedBanner
                        .padding(.bottom, 174)
                }
                .transition(.opacity)
            }

            // ---- More menu sheet ----
            if showMoreSheet {
                moreSheetOverlay
            }

            // ---- Camera modal ----
            if showCamera {
                CameraView(
                    onCapture: { image in handleCameraCapture(image: image) },
                    onClose: { showCamera = false }
                )
                .transition(.opacity)
            }

            // ---- Full-screen tour map ----
            if showTourMap {
                TourMapView(
                    trail: trail,
                    activeStopIdx: stopIdx,
                    onClose: { showTourMap = false }
                )
                .transition(.opacity)
            }
        }
    }

    // MARK: - Top progress / stop hero

    private var topProgressArea: some View {
        ZStack {
            switch phase {
            case .atStop:
                stopHeroCard
                    .padding(.horizontal, 24)
                    .padding(.top, 70)
                    .transition(.opacity.combined(with: .scale(scale: 0.985)))
            case .between, .approaching:
                progressBar
                    .padding(.horizontal, 24)
                    .padding(.top, 70)
                    .transition(.opacity)
            case .complete:
                // Hidden in terminal state — the completion card takes
                // over the screen centrally; nothing competes for the
                // top progress slot.
                EmptyView()
            }
        }
    }

    private var stopHeroCard: some View {
        Button {
            showTourMap = true
        } label: {
            ZStack(alignment: .bottomLeading) {
                AsyncImage(url: currentStop.imageURL) { phase in
                    switch phase {
                    case .success(let img): img.resizable().scaledToFill()
                    default: AppColor.ink25
                    }
                }
                .frame(maxWidth: .infinity, maxHeight: 156)
                .clipped()

                LinearGradient(
                    colors: [.clear, .black.opacity(0.85)],
                    startPoint: UnitPoint(x: 0.5, y: 0.3),
                    endPoint: .bottom
                )

                VStack(alignment: .leading, spacing: 3) {
                    HStack(spacing: 6) {
                        Text("Arrived")
                            .foregroundStyle(AppColor.lime)
                        Text("·")
                            .foregroundStyle(AppColor.lime.opacity(0.6))
                        Text("Stop \(currentStop.number) of \(trail.stops.count)")
                            .foregroundStyle(AppColor.lime.opacity(0.85))
                    }
                    .font(AppFont.sans(9.5, .heavy))
                    .tracking(1.6)
                    .textCase(.uppercase)

                    Text(currentStop.name)
                        .font(AppFont.sans(20, .bold))
                        .foregroundStyle(AppColor.ink100)
                        .tracking(-0.4)
                        .lineLimit(2)
                }
                .padding(16)
            }
            .frame(height: 156)
            .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
            .shadow(color: .black.opacity(0.4), radius: 14, x: 0, y: 14)
        }
        .buttonStyle(.plain)
    }

    private var progressBar: some View {
        Button {
            showTourMap = true
        } label: {
            VStack(spacing: 12) {
                // Markers + position pin
                ZStack {
                    Rectangle()
                        .frame(height: 1)
                        .foregroundStyle(AppColor.ink100.opacity(0.10))

                    GeometryReader { geo in
                        ForEach(trail.stops.indices, id: \.self) { i in
                            stopMarker(idx: i)
                                .position(
                                    x: geo.size.width * (trail.stopProgressPositions[safe: i] ?? 0),
                                    y: geo.size.height / 2
                                )
                        }
                        if phase != .atStop {
                            // Position pin slides between current and next
                            Circle()
                                .fill(AppColor.lime)
                                .frame(width: 11, height: 11)
                                .shadow(color: AppColor.lime.opacity(0.55), radius: 6)
                                .position(
                                    x: geo.size.width * pinFraction,
                                    y: geo.size.height / 2
                                )
                                .animation(.linear(duration: betweenSeconds + approachingSeconds - 0.2),
                                           value: pinFraction)
                        }
                    }
                    .frame(height: 12)
                }
                .frame(height: 12)

                Text(progressLabel)
                    .font(AppFont.sans(10, .semibold))
                    .tracking(1.8)
                    .textCase(.uppercase)
                    .foregroundStyle(AppColor.ink100.opacity(0.5))
                    .lineLimit(1)
            }
            .padding(.vertical, 9)
            .padding(.horizontal, 14)
            .background(AppColor.ink100.opacity(0.025), in: RoundedRectangle(cornerRadius: 12))
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .stroke(AppColor.ink100.opacity(0.06), lineWidth: 1)
            )
        }
        .buttonStyle(.plain)
    }

    @ViewBuilder
    private func stopMarker(idx: Int) -> some View {
        if idx < stopIdx {
            Circle()
                .fill(AppColor.ink100.opacity(0.30))
                .frame(width: 5, height: 5)
        } else if idx == stopIdx, phase == .atStop {
            Circle()
                .fill(AppColor.lime)
                .frame(width: 8, height: 8)
                .shadow(color: AppColor.lime.opacity(0.45), radius: 7)
        } else if idx == stopIdx + 1, phase == .approaching {
            Circle()
                .fill(AppColor.lime.opacity(0.18))
                .overlay(Circle().stroke(AppColor.lime, lineWidth: 1.5))
                .frame(width: 8, height: 8)
        } else {
            Circle()
                .fill(AppColor.ink100.opacity(0.18))
                .frame(width: 4, height: 4)
        }
    }

    private var pinFraction: CGFloat {
        let total = trail.stops.count
        guard total > 0 else { return 0.5 }
        let nextIdx = min(stopIdx + 1, total - 1)
        let curPos  = trail.stopProgressPositions[safe: stopIdx] ?? 0.5
        let nextPos = trail.stopProgressPositions[safe: nextIdx] ?? curPos
        switch phase {
        case .atStop, .complete:    return curPos
        case .between, .approaching: return nextPos
        }
    }

    private var progressLabel: String {
        switch phase {
        case .atStop:
            return "\(currentStop.name) · Stop \(currentStop.number) of \(trail.stops.count)"
        case .between:
            let nextName = nextStop.name
            let dist = (trail.segmentLabels[safe: stopIdx] ?? "").components(separatedBy: " · ").first ?? ""
            return "Walking · \(dist) to \(nextName)"
        case .approaching:
            return "Approaching · \(nextStop.name)"
        case .complete:
            return "Tour complete"
        }
    }

    // MARK: - Center content

    /// Display rules:
    ///   • Companion ANSWER (foreground, lime "Companion" eyebrow):
    ///       - shown whenever Gemma is generating an answer, or while
    ///         Kokoro is speaking that answer back
    ///       - takes priority over the background narration lane
    ///   • Tour NARRATION (background, lyric position):
    ///       - while Kokoro is reading trail-guide content, the live
    ///         caption builds word-by-word in the lyric area
    ///       - when nothing is being narrated, falls back to the silent
    ///         auto-rotating lyric stack at .atStop, or the quiet
    ///         indicator between stops
    ///
    /// We never show both lanes' content simultaneously — the foreground
    /// answer lane visually takes over when active.
    /// Two-lane display, no third type:
    ///   • Companion's reply (foreground) — Gemma generating an answer
    ///     OR Kokoro speaking that answer back. Lime "Companion"
    ///     eyebrow above the live text.
    ///   • Lyrics (background) — Kokoro narrating tour-guide content.
    ///     Live caption builds word-by-word in sync with the audio.
    ///
    /// When neither is in flight (silent gap between narrations, or
    /// between/approaching phase), the center is intentionally empty —
    /// there is no static placeholder text. The walking view's progress
    /// bar and bottom controls give the user something to look at, and
    /// the next narration will fill the lyric area when it arrives.
    @ViewBuilder
    private var centerContent: some View {
        if phase == .complete {
            // Terminal state — takes priority over every other lane.
            // No Asks, no narration, no quiet indicator — just the
            // summary card and the journal CTA.
            completionCard
        } else if showAnswerLane {
            // FOREGROUND — Companion reply (Q&A)
            answerLaneView
                .opacity(isHolding ? 0.05 : 1.0)
        } else if currentlySpeaking == .narration {
            // BACKGROUND — Lyrics (what Kokoro is narrating).
            // Rendered as soon as narration is queued, even if the
            // caption is briefly empty during the 1–2 s model-load
            // window — that empty space is fine; better than flashing
            // unrelated text.
            narrationLaneView(text: tts.currentCaption)
                .opacity(isHolding ? 0.05 : 1.0)
        } else if phase != .atStop {
            // Between / approaching — center quiet indicator
            // (this is the small "Walking to … 0.4 mi" stop indicator;
            //  not text, just the next-stop label, so it doesn't conflict
            //  with the two-lane rule).
            quietIndicator
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .opacity(isHolding ? 0.0 : 1.0)
        }
        // else: at-stop with nothing speaking → empty by design.
    }

    /// True while a Q&A reply should occupy the foreground lane:
    /// either Gemma is generating, the answer text is streaming in, or
    /// Kokoro is speaking the finished answer back.
    private var showAnswerLane: Bool {
        if isAnswering { return true }
        if !answerText.isEmpty { return true }
        if currentlySpeaking == .answer { return true }
        return false
    }

    /// FOREGROUND: companion reply.
    ///
    /// Display rule: prefer the full streamed `answerText` (Gemma's
    /// finished response) and KEEP it on screen while Kokoro speaks.
    /// We don't switch to the live caption mid-answer because that
    /// produced a confusing "rewind" effect — the user already read the
    /// full answer once during streaming; rebuilding it word-by-word
    /// from "Welcome…" while Kokoro is reading makes the screen feel
    /// like it's stuttering.
    ///
    /// While Gemma is still streaming and `answerText` is empty, fall
    /// back to ellipsis. Rolling-windowed so a long answer never grows
    /// past ~4 lines.
    /// FOREGROUND: companion reply. Same auto-scrolling-ScrollView
    /// approach as `narrationLaneView` — see its docs for why we don't
    /// use lineLimit + truncationMode here.
    private var answerLaneView: some View {
        let displayText: String = answerText.isEmpty ? "…" : answerText
        let eyebrow = (isAnswering && currentlySpeaking != .answer)
            ? "Companion · thinking"
            : "Companion"
        let answerAnchor = captionAnchorID + ".answer"

        return VStack(spacing: 14) {
            Text(eyebrow)
                .eyebrowStyle(AppColor.lime)
            ScrollViewReader { proxy in
                ScrollView(.vertical, showsIndicators: false) {
                    Text(displayText)
                        .font(AppFont.sans(22, .semibold))
                        .foregroundStyle(AppColor.ink100)
                        .tracking(-0.3)
                        .multilineTextAlignment(.center)
                        .lineSpacing(4)
                        .padding(.horizontal, 28)
                        .frame(maxWidth: .infinity, alignment: .center)
                        .id(answerAnchor)
                }
                .scrollDisabled(true)
                .frame(maxWidth: .infinity)
                // 320pt scroll + 12pt eyebrow + 14pt spacing = 346pt
                // VStack content. From padding-top 240 → bottom y=586.
                .frame(height: 320)
                .onChange(of: displayText) { _, _ in
                    Task { @MainActor in
                        try? await Task.sleep(for: .milliseconds(20))
                        withAnimation(.linear(duration: 0.12)) {
                            proxy.scrollTo(answerAnchor, anchor: .bottom)
                        }
                    }
                }
                .onAppear {
                    Task { @MainActor in
                        try? await Task.sleep(for: .milliseconds(20))
                        proxy.scrollTo(answerAnchor, anchor: .bottom)
                    }
                }
            }
        }
        .padding(.top, 240)
        // Pin to ZStack top edge — see narrationLaneView for why this
        // matters (default ZStack alignment would center-stack and
        // push the lyric bottom into the mic button).
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)
    }

    /// BACKGROUND: tour narration caption.
    ///
    /// Implemented as an auto-scrolling ScrollView, NOT a Text with
    /// lineLimit. Reason: SwiftUI's `Text(...).lineLimit(N)
    /// .truncationMode(.head)` only affects WHERE the ellipsis appears
    /// on the *last* visible line — it doesn't pick which N lines of
    /// the content actually render. So with long captions (e.g. the
    /// intro), the FIRST N-1 lines render normally and only the last
    /// one truncates; newer content past line N never appears. Net
    /// effect: oldest lines freeze at the top.
    ///
    /// The ScrollView fix:
    ///   • Renders the full caption inside a fixed-height scroll area.
    ///   • `ScrollViewReader` lets us programmatically scroll to the
    ///     bottom on every caption change, so the newest line is
    ///     always visible at the bottom of the lyric area.
    ///   • Older content stays in the (unseen) scroll buffer above —
    ///     looks visually like text scrolling up as new lines arrive.
    ///   • `scrollDisabled(true)` keeps the user from manually
    ///     scrolling and fighting the auto-scroll. (We can revisit
    ///     this if there's demand to scroll back through history.)
    private func narrationLaneView(text: String) -> some View {
        let displayText: String = text.isEmpty ? narrationPreamble : text
        let isPreamble = text.isEmpty && !narrationPreamble.isEmpty

        return ScrollViewReader { proxy in
            ScrollView(.vertical, showsIndicators: false) {
                Text(displayText)
                    .font(AppFont.sans(24, .semibold))
                    .foregroundStyle(AppColor.ink100)
                    .tracking(-0.4)
                    .multilineTextAlignment(.center)
                    .lineSpacing(4)
                    .opacity(isPreamble ? 0.55 : 0.85)
                    .padding(.horizontal, 28)
                    .frame(maxWidth: .infinity, alignment: .center)
                    .id(captionAnchorID)
            }
            .scrollDisabled(true)
            .frame(maxWidth: .infinity)
            .frame(height: 360)
            // 240 = 226 (hero card bottom) + 14 visual margin. The
            // hero card has a soft drop shadow that extends ~28pt
            // below its rect; 14pt of clean margin keeps the lyric
            // top from butting against it. Lyric bottom lands at
            // 240+360 = 600, comfortably above the mic-button shadow
            // upper edge at ~654.
            .padding(.top, 240)
            // Pin the lane to the ZStack's top edge so the padding
            // measurement actually anchors to y=0 (default ZStack
            // alignment is .center, which would float the whole block
            // down ~110pt and shove the bottom into the mic button).
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)
            .onChange(of: displayText) { _, _ in
                pinScrollToBottom(proxy)
            }
            .onAppear {
                pinScrollToBottom(proxy)
            }
        }
    }

    /// ID we attach to the caption text so `ScrollViewProxy.scrollTo`
    /// can reach it. Unique-by-instance so it stays stable across renders.
    private var captionAnchorID: String { "lyric-caption-anchor" }

    /// Scroll the lyric / answer lane such that the bottom edge of the
    /// caption text aligns with the bottom of the visible scroll area.
    /// Bounced through the next runloop turn so SwiftUI has a chance
    /// to lay out the new (longer) text before we ask for its bottom.
    private func pinScrollToBottom(_ proxy: ScrollViewProxy) {
        Task { @MainActor in
            try? await Task.sleep(for: .milliseconds(20))
            withAnimation(.linear(duration: 0.12)) {
                proxy.scrollTo(captionAnchorID, anchor: .bottom)
            }
        }
    }

    private var quietIndicator: some View {
        VStack(spacing: 14) {
            Text(phase == .approaching ? "Approaching" : "Walking to")
                .eyebrowStyle(phase == .approaching ? AppColor.lime : AppColor.ink60)
                .padding(.bottom, 0)

            Text(nextStop.name)
                .font(AppFont.sans(26, .bold))
                .tracking(-0.5)
                .foregroundStyle(phase == .approaching ? AppColor.lime : AppColor.ink100)
                .multilineTextAlignment(.center)
                .lineLimit(2)

            if phase == .between {
                Text(trail.segmentLabels[safe: stopIdx] ?? "")
                    .font(AppFont.sans(12.5, .medium))
                    .foregroundStyle(AppColor.ink60)
                    .padding(.top, 14)
            }

            // "ON THE WAY" engagement panel — surfaces the `lookFor`
            // prompt from the stop the user just left, inviting them
            // to notice something specific on the walk to the next
            // stop. The corresponding `payoff` will play as the first
            // line of narration on arrival.
            //
            // Source: design/mockups.html `.wq-lookfor` block. Auto-
            // hides via the `if let` when the previous stop has no
            // lookFor (e.g. final segment after the trail's last
            // stop's lookFor, or trails that didn't author one).
            if let lookFor = currentStop.lookFor {
                VStack(spacing: 6) {
                    Text("On the way")
                        .eyebrowStyle(AppColor.lime)
                    Text(lookFor)
                        .font(AppFont.sans(15, .medium))
                        .foregroundStyle(AppColor.ink80)
                        .multilineTextAlignment(.center)
                        .lineSpacing(3)
                        .padding(.horizontal, 4)
                }
                .padding(.top, 28)
            }
        }
        .padding(.horizontal, 32)
    }

    // MARK: - Completion card (terminal state)

    /// Shown when `phase == .complete`. Mirrors the mockup's terminal
    /// state: lime-bordered checkmark + "TOUR COMPLETE" eyebrow +
    /// "You walked the loop" + summary stats derived from the active
    /// trail's metadata (no more hardcoded "2.0 mi · 5 stops · 1 hr
    /// 12 min" — the previous mockup's known limitation) + a lime
    /// "Open journal" CTA that routes to the journal screen.
    private var completionCard: some View {
        VStack(spacing: 22) {
            // Lime-bordered checkmark glyph
            ZStack {
                Circle()
                    .stroke(AppColor.lime, lineWidth: 1.5)
                    .frame(width: 86, height: 86)
                    .shadow(color: AppColor.lime.opacity(0.35), radius: 18)
                Image(systemName: "checkmark")
                    .font(.system(size: 32, weight: .semibold))
                    .foregroundStyle(AppColor.lime)
            }

            VStack(spacing: 8) {
                Text("Tour complete")
                    .eyebrowStyle(AppColor.lime)

                Text("You walked the loop")
                    .font(AppFont.sans(24, .bold))
                    .tracking(-0.4)
                    .foregroundStyle(AppColor.ink100)
                    .multilineTextAlignment(.center)

                Text(completionSummary)
                    .font(AppFont.sans(13, .medium))
                    .foregroundStyle(AppColor.ink60)
                    .multilineTextAlignment(.center)
                    .padding(.top, 4)
            }

            Button {
                router.endTour()  // routes to .journal; onDisappear cleans up
            } label: {
                Text("Open journal")
                    .font(AppFont.sans(15, .semibold))
                    .foregroundStyle(AppColor.limeText)
                    .padding(.horizontal, 28)
                    .padding(.vertical, 14)
                    .background(AppColor.lime, in: Capsule())
            }
            .buttonStyle(LimePressStyle())
            .padding(.top, 8)
        }
        .padding(.horizontal, 32)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    /// Stats line derived from the active trail's metadata —
    /// e.g. "2 mi · 5 stops · 1 hr" or "1.1 mi · 3 stops · 30 min".
    private var completionSummary: String {
        let miles = trail.distanceMiles == floor(trail.distanceMiles)
            ? String(format: "%.0f", trail.distanceMiles)
            : String(format: "%.1f", trail.distanceMiles)
        return "\(miles) mi · \(trail.stops.count) stops · \(formattedDuration)"
    }

    /// "30 min" / "1 hr" / "1 hr 12 min" — friendlier than always
    /// rendering minutes when the duration crosses an hour.
    private var formattedDuration: String {
        let m = trail.durationMinutes
        if m < 60 { return "\(m) min" }
        let h = m / 60
        let r = m % 60
        return r == 0 ? "\(h) hr" : "\(h) hr \(r) min"
    }

    // MARK: - Photo context bar

    private var photoContextBar: some View {
        HStack(spacing: 12) {
            // Real captured thumbnail. Falls back to a placeholder
            // glyph if (somehow) the strip is shown without an image.
            Group {
                if let img = capturedImage {
                    Image(uiImage: img)
                        .resizable()
                        .scaledToFill()
                } else {
                    AppColor.ink25
                        .overlay(
                            Image(systemName: "photo")
                                .foregroundStyle(AppColor.ink60)
                        )
                }
            }
            .frame(width: 56, height: 56)
            .clipShape(RoundedRectangle(cornerRadius: 9, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 9).stroke(AppColor.hairline, lineWidth: 1)
            )

            VStack(alignment: .leading, spacing: 4) {
                HStack(spacing: 7) {
                    Circle()
                        .fill(AppColor.lime)
                        .frame(width: 5, height: 5)
                        .shadow(color: AppColor.lime.opacity(0.7), radius: 3)
                    Text("Photo in context")
                        .font(AppFont.sans(9.5, .heavy))
                        .tracking(1.6)
                        .textCase(.uppercase)
                        .foregroundStyle(AppColor.lime)
                }
                Text("Hold Ask to follow up about this")
                    .font(AppFont.sans(12, .medium))
                    .foregroundStyle(AppColor.ink80)
            }

            Spacer()

            Button {
                dismissPhotoContext()
            } label: {
                Image(systemName: "xmark")
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundStyle(AppColor.ink60)
                    .frame(width: 28, height: 28)
                    .background(Color.white.opacity(0.05), in: Circle())
            }
            .buttonStyle(.plain)
        }
        .padding(8)
        .background(AppColor.glassDark88, in: RoundedRectangle(cornerRadius: 14, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 14)
                .stroke(AppColor.lime.opacity(0.32), lineWidth: 1)
        )
        .shadow(color: .black.opacity(0.35), radius: 12, x: 0, y: 8)
        .shadow(color: AppColor.lime.opacity(0.06), radius: 12)
    }

    // MARK: - Live ask transcript overlay

    private var askTranscriptOverlay: some View {
        VStack(spacing: 14) {
            HStack(spacing: 8) {
                Circle()
                    .fill(AppColor.lime)
                    .frame(width: 6, height: 6)
                    .shadow(color: AppColor.lime.opacity(0.7), radius: 4)
                    .modifier(BreathePulse())
                Text("Listening")
                    .font(AppFont.sans(10.5, .heavy))
                    .tracking(2.0)
                    .textCase(.uppercase)
                    .foregroundStyle(AppColor.lime.opacity(0.55))
            }

            Text(transcriptDisplay)
                .font(AppFont.sans(26, .semibold))
                .foregroundStyle(AppColor.lime)
                .tracking(-0.4)
                .multilineTextAlignment(.center)
                .lineLimit(4)
        }
        .padding(.horizontal, 28)
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)
        .padding(.top, UIScreen.main.bounds.height * 0.40)
    }

    private var transcriptDisplay: String {
        let t = speech.transcript
        return t.isEmpty ? "…" : t
    }

    // MARK: - Bottom controls

    private var bottomControls: some View {
        HStack(spacing: 28) {
            // Camera
            Button {
                showCamera = true
            } label: {
                Image(systemName: "camera")
                    .font(.system(size: 20, weight: .medium))
                    .foregroundStyle(AppColor.ink100)
                    .frame(width: 56, height: 56)
                    .background(.white.opacity(0.05), in: Circle())
                    .overlay(Circle().stroke(AppColor.ink100.opacity(0.18), lineWidth: 1))
            }
            .buttonStyle(.plain)

            // Mic — large, lime, hold-to-speak
            micButton

            // More
            Button {
                showMoreSheet.toggle()
            } label: {
                Image(systemName: isPaused ? "play.fill" : "pause.fill")
                    .font(.system(size: 18, weight: .semibold))
                    .foregroundStyle(isPaused ? AppColor.lime : AppColor.ink100)
                    .frame(width: 56, height: 56)
                    .background(
                        showMoreSheet
                            ? AppColor.lime.opacity(0.10)
                            : AppColor.ink100.opacity(0.05)
                        , in: Circle()
                    )
                    .overlay(
                        Circle().stroke(
                            showMoreSheet || isPaused ? AppColor.lime.opacity(0.45) : AppColor.ink100.opacity(0.18),
                            lineWidth: 1
                        )
                    )
            }
            .buttonStyle(.plain)
        }
    }

    private var micButton: some View {
        ZStack {
            // Ripple rings while holding
            if isHolding {
                Circle()
                    .stroke(AppColor.lime.opacity(0.55), lineWidth: 2)
                    .frame(width: 88, height: 88)
                    .modifier(RippleAnim(delay: 0))
                Circle()
                    .stroke(AppColor.lime.opacity(0.55), lineWidth: 2)
                    .frame(width: 88, height: 88)
                    .modifier(RippleAnim(delay: 1))
            }

            // Soft glow background while holding
            Circle()
                .fill(AppColor.lime)
                .frame(width: 88, height: 88)
                .shadow(color: AppColor.lime.opacity(isHolding ? 0.45 : 0.0), radius: 50)
                .scaleEffect(isHolding ? 1.06 : 1.0)
                .overlay(
                    Image(systemName: "mic.fill")
                        .font(.system(size: 28, weight: .semibold))
                        .foregroundStyle(AppColor.limeText)
                        .scaleEffect(isHolding ? 1.06 : 1.0)
                )
                .animation(.easeInOut(duration: 0.18), value: isHolding)
        }
        .gesture(holdGesture)
        // Disabled while we're streaming a response or while Kokoro is
        // actively speaking — prevents starting a second turn before the
        // first one finishes.
        .opacity(canHold ? 1.0 : 0.5)
        .allowsHitTesting(canHold)
    }

    private var canHold: Bool {
        speech.isAuthorized
            && !isAnswering
            && !tts.isRunning
            && tts.isReady
            && !gemma.status.contains("Loading")
    }

    private var holdGesture: some Gesture {
        DragGesture(minimumDistance: 0)
            .onChanged { _ in
                guard canHold, !isHolding else { return }
                startHold()
            }
            .onEnded { _ in
                guard isHolding else { return }
                endHold()
            }
    }

    // MARK: - Paused banner

    private var pausedBanner: some View {
        HStack(spacing: 8) {
            Image(systemName: "pause.fill")
                .font(.system(size: 8, weight: .heavy))
            Text("Paused")
                .font(AppFont.sans(11, .heavy))
                .tracking(1.8)
                .textCase(.uppercase)
        }
        .foregroundStyle(AppColor.ink80)
        .padding(.horizontal, 14)
        .padding(.vertical, 6)
        .background(Color(red: 20/255, green: 21/255, blue: 18/255).opacity(0.85), in: Capsule())
        .overlay(Capsule().stroke(AppColor.hairlineHi, lineWidth: 1))
    }

    // MARK: - More menu sheet

    private var moreSheetOverlay: some View {
        ZStack {
            // Dismiss area
            Color.clear
                .contentShape(Rectangle())
                .onTapGesture { showMoreSheet = false }

            VStack {
                Spacer()
                HStack {
                    Spacer()
                    moreSheet
                        .padding(.trailing, 16)
                        .padding(.bottom, 168)
                }
            }
        }
    }

    private var moreSheet: some View {
        VStack(spacing: 0) {
            Button {
                togglePause()
                showMoreSheet = false
            } label: {
                moreSheetItem(
                    icon: isPaused ? "play.fill" : "pause.fill",
                    label: isPaused ? "Resume tour" : "Pause tour",
                    danger: false
                )
            }
            .buttonStyle(.plain)

            Rectangle()
                .frame(height: 1)
                .foregroundStyle(AppColor.hairline)
                .padding(.horizontal, 8)

            Button {
                endTour()
                showMoreSheet = false
            } label: {
                moreSheetItem(
                    icon: "stop.fill",
                    label: "End tour",
                    danger: true
                )
            }
            .buttonStyle(.plain)
        }
        .padding(6)
        .frame(width: 240)
        .background(
            Color(red: 20/255, green: 21/255, blue: 18/255).opacity(0.96),
            in: RoundedRectangle(cornerRadius: 16, style: .continuous)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 16)
                .stroke(AppColor.hairlineHi, lineWidth: 1)
        )
        .shadow(color: .black.opacity(0.55), radius: 16, x: 0, y: 16)
    }

    private func moreSheetItem(icon: String, label: String, danger: Bool) -> some View {
        let color: Color = danger ? Color(red: 0.91, green: 0.72, blue: 0.54) : AppColor.ink100
        return HStack(spacing: 12) {
            Image(systemName: icon)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(color)
                .frame(width: 28, height: 28)
                .background(Color.white.opacity(0.06), in: Circle())
            Text(label)
                .font(AppFont.sans(14.5, .semibold))
                .foregroundStyle(color)
                .tracking(-0.2)
            Spacer()
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 12)
    }

    // MARK: - Actions

    private func startHold() {
        // Interrupt any ongoing tour-guide narration and capture how
        // far it got so we can resume the unspoken remainder later.
        interruptNarrationForQuestion()

        // Pause the auto-tour phase timer for the duration of the
        // interaction. If we didn't, the timer could fire mid-hold and
        // kick off a new "Arriving at <stop>…" narration the user
        // can't hear because they're focused on their question — and
        // worse, that narration's TTS synth would still be running
        // when runAsk tries to speak the answer, silently dropping
        // the answer's `tts.synthesize` and stranding the tour with
        // a stale narrationFullText (the "stuck at Layered Cliffs"
        // bug). scheduleNextPhase reruns at the end of every Ask flow
        // so the timer comes back on its own.
        phaseTimer?.invalidate()
        phaseTimer = nil

        isHolding = true
        do {
            try speech.startRecording()
        } catch {
            // Permissions/availability errors surface in speech.status.
        }
    }

    private func endHold() {
        speech.stopRecording()
        isHolding = false

        Task {
            // Wait briefly for the final SFSpeechRecognizer result to arrive.
            try? await Task.sleep(for: .milliseconds(600))
            let text = speech.transcript.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else {
                // Nothing captured. Two cleanups depending on what we
                // interrupted on the way in:
                //   • narrationPaused → resumeNarrationIfNeeded brings
                //     the narration back; the narration's natural end
                //     will re-arm the phase timer via scheduleNextPhase.
                //   • otherwise → we killed the phase timer in
                //     startHold and there's nothing in flight, so
                //     re-arm it ourselves.
                await MainActor.run {
                    if narrationPaused {
                        resumeNarrationIfNeeded()
                    } else {
                        scheduleNextPhase()
                    }
                }
                return
            }
            await MainActor.run {
                runAsk(prompt: text)
            }
        }
    }

    /// Phase 3b — same lazy-load + stream + unload + speak flow as
    /// DebugView, with one twist: we pick the loader based on whether
    /// a photo is in context.
    ///
    ///   • Photo present → load the multimodal VLM path; pass UIImage
    ///     down to GemmaService.streamResponse(prompt:image:).
    ///   • Photo absent  → load the lighter text-only path; image is
    ///     nil; same streamResponse with image: nil.
    ///
    /// GemmaService unloads the previously-loaded kind if it doesn't
    /// match, so consecutive same-kind Asks reuse weights.
    private func runAsk(prompt: String) {
        isAnswering = true
        answerText = ""
        var photoForThisTurn = (showPhotoContext ? capturedImage : nil)
        let kind: GemmaService.LoadedKind = (photoForThisTurn != nil) ? .vlm : .text

        Task {
            do {
                // RAG retrieval BEFORE Gemma loads. Text-only path only
                // for v1 — VLM Asks already pay ~196 image tokens, and
                // stacking RAG chunks on top exceeds our 1024 KV budget.
                // If no subject is active or retrieval errors, we just
                // proceed without an injected chunk (graceful fallback).
                if photoForThisTurn == nil, rag.activeSubject != nil {
                    do {
                        let chunks = try await rag.retrieve(query: prompt, k: 1)
                        let block = rag.formatChunksForPrompt(chunks)
                        if block.isEmpty {
                            print("[RAG] no block to inject (chunks=\(chunks.count))")
                        } else {
                            print("[RAG] injecting \(block.count) chars into gemma.ragContext")
                        }
                        await MainActor.run { gemma.ragContext = block }
                    } catch {
                        // Retrieval failed (corpus missing, model not
                        // ready, etc.) — log and continue without RAG.
                        // Gemma will answer from its own knowledge.
                        print("[RAG] retrieve failed: \(error.localizedDescription)")
                    }
                } else if photoForThisTurn != nil {
                    print("[RAG] skipped: VLM turn (has photo)")
                } else {
                    print("[RAG] skipped: no active subject")
                }

                try await gemma.loadIfNeeded(kind)

                guard let stream = gemma.streamResponse(
                    prompt: prompt,
                    image: photoForThisTurn
                ) else {
                    answerText = "[error: Gemma session not ready]"
                    isAnswering = false
                    return
                }

                var fullText = ""
                for try await chunk in stream {
                    fullText += chunk
                    await MainActor.run { answerText = fullText }
                }

                if photoForThisTurn != nil {
                    photoForThisTurn = nil
                    await MainActor.run {
                        showPhotoContext = false
                        capturedImage = nil
                    }
                }

                // Free Gemma between turns (per CLAUDE.md / commit e681ee2).
                gemma.unload()

                // Speak the response. Mark this synth as an .answer so
                // the UI shows it in the foreground "Companion" lane,
                // distinct from the ambient .narration lane. We wait for
                // Kokoro to finish playing before resuming any paused
                // tour narration — otherwise the bridge phrase ("Let me
                // continue my explanation.") would step on the answer.
                if !fullText.isEmpty {
                    await MainActor.run { currentlySpeaking = .answer }
                    tts.synthesize(text: fullText, speed: 1.0)
                    await waitForTTSPlaybackToFinish()
                }
                await MainActor.run {
                    answerText = ""
                    isAnswering = false

                    // If a tour narration was paused for this question,
                    // resume it from the unspoken remainder with a
                    // bridge phrase. Otherwise just let the phase timer
                    // pick back up — there's no static fallback text.
                    if narrationPaused { resumeNarrationIfNeeded() }
                    scheduleNextPhase()
                }
            } catch {
                await MainActor.run {
                    gemma.unload()
                    photoForThisTurn = nil
                    answerText += "\n\n[error: \(error.localizedDescription)]"
                    showPhotoContext = false
                    capturedImage = nil
                    isAnswering = false
                    // Try to resume narration even on error so the user
                    // doesn't end up stuck silent.
                    if narrationPaused { resumeNarrationIfNeeded() }
                    scheduleNextPhase()
                }
            }
        }
    }

    /// Wait for Kokoro to FULLY play the current synthesis.
    ///
    /// Two phases because `tts.synthesize` is fire-and-forget — work
    /// happens on a background serial queue, so right after the call
    /// returns `isSpeaking` is still false (no audio yet). A naive
    /// `while isSpeaking` would exit instantly and the caller would
    /// clear the on-screen answer text BEFORE Kokoro had even started
    /// speaking — the "flash answer, disappear, reappear when Kokoro
    /// reads" bug.
    ///
    /// **No timeouts.** We trust the state machine in ValidationRunner:
    ///   • Phase 1 ends when isSpeaking flips true (first PCM buffer
    ///     scheduled), OR when isRunning flips false without that ever
    ///     happening — i.e. synth aborted/errored before producing any
    ///     audio.
    ///   • Phase 2 ends when isSpeaking flips false. That is guaranteed
    ///     to happen via one of three paths in ValidationRunner:
    ///       1. `dataPlayedBack` callback on the last scheduled buffer
    ///          (normal completion)
    ///       2. `stop()` called from elsewhere (user interrupt)
    ///       3. the synth-error catch block (mid-stream failure)
    ///     If none of those fire we have a real bug, and a timeout
    ///     would just paper over it by silently clearing the answer.
    @MainActor
    private func waitForTTSPlaybackToFinish() async {
        // Phase 1 — wait for audio to actually start, or for synth to
        // abort before it could.
        while !tts.isSpeaking, tts.isRunning {
            try? await Task.sleep(for: .milliseconds(50))
        }
        guard tts.isSpeaking else { return }

        // Phase 2 — wait for audio to finish.
        while tts.isSpeaking {
            try? await Task.sleep(for: .milliseconds(100))
        }
    }

    /// Called from CameraView with a real downscaled `UIImage`.
    /// Stores the image, closes the modal, and brings up the photo-
    /// context strip so the user can ask a follow-up question.
    private func handleCameraCapture(image: UIImage) {
        capturedImage = image
        showCamera = false
        showToast("Captured")
        Task {
            try? await Task.sleep(for: .milliseconds(280))
            await MainActor.run { showPhotoContext = true }
        }
    }

    /// Drop the photo from memory and hide the strip.
    private func dismissPhotoContext() {
        showPhotoContext = false
        capturedImage = nil
    }

    private func showToast(_ msg: String) {
        toastTask?.cancel()
        toastMessage = msg
        toastTask = Task {
            try? await Task.sleep(for: .milliseconds(1400))
            await MainActor.run { toastMessage = nil }
        }
    }

    private func togglePause() {
        isPaused.toggle()
        if isPaused {
            stopTourCycle()
            tts.stop()                 // halt any in-flight narration
            if narrationFullText != nil, !narrationPaused {
                // Treat a pause-during-narration like a question-driven
                // pause so resume-with-bridge fires when the user unpauses.
                narrationDelivered = tts.currentCaption
                narrationPaused = true
            }
        } else {
            // Resume order: if we have a paused narration, restart it
            // first (sets currentlySpeaking = .narration). Then schedule
            // the phase timer; it will short-circuit if narration is
            // still active and pick up automatically when narration ends.
            if narrationPaused { resumeNarrationIfNeeded() }
            scheduleNextPhase()
        }
    }

    private func endTour() {
        stopTourCycle()
        tts.stop()
        gemma.reset()              // wipe conversation history at end of tour
        gemma.setActiveContext(trail: nil, stopIdx: nil)  // drop trail/stop framing
        capturedImage = nil        // drop any captured photo
        showPhotoContext = false
        narrationFullText = nil
        narrationDelivered = ""
        narrationPaused = false
        currentlySpeaking = .none
        router.endTour()
    }

    // MARK: - Tour cycle (timer-driven prototype)

    private func startTourCycle() {
        stopIdx = 0
        phase = .atStop
        // Hand the LM the trail + first-stop framing BEFORE the user
        // can ask anything. Without this, the very first Ask would hit
        // a Gemma that doesn't know which trail it's on.
        gemma.setActiveContext(trail: trail, stopIdx: stopIdx)

        // PoC: hardcode the RAG subject to .geology so retrieval runs
        // end-to-end without a UI. The first runAsk on this tour will
        // trigger swift-embeddings' MiniLM download from HuggingFace
        // (~80 MB, one-time per device, needs network on first launch).
        // TODO: replace with a subject-picker UI; consider auto-pick
        // per trail (Kildoo/HellsHollow → geology+plants, Tranquil →
        // plants by default) once the picker is built.
        do {
            try rag.setActiveSubject(.geology)
        } catch {
            print("[RAG] setActiveSubject failed: \(error.localizedDescription)")
        }
        // Speak the trail intro on Begin. Phase timer is paused while
        // narration plays — see scheduleNextPhase.
        speakNarration(
            trail.intro,
            preamble: "Let's step into the trail. Take a breath…"
        )
        scheduleNextPhase()
    }

    private func stopTourCycle() {
        phaseTimer?.invalidate()
        phaseTimer = nil
    }

    /// Schedule the next phase advance. Pauses if narration or a Q&A
    /// answer is in flight — we don't want to ramp through stops while
    /// the user is hearing/being answered something. Also early-returns
    /// if the tour is `complete` (terminal state, no further timer).
    private func scheduleNextPhase() {
        phaseTimer?.invalidate()
        if isPaused { return }
        if phase == .complete { return } // terminal — don't re-arm
        if narrationActive { return }   // wait for narration to finish
        if isAnswering { return }        // wait for answer to play out

        let delay: Double = {
            switch phase {
            case .atStop:       return atStopSeconds
            case .between:      return betweenSeconds
            case .approaching:  return approachingSeconds
            case .complete:     return .infinity   // unreachable — guarded above
            }
        }()
        phaseTimer = Timer.scheduledTimer(withTimeInterval: delay, repeats: false) { _ in
            Task { @MainActor in
                advancePhase()
            }
        }
    }

    private func advancePhase() {
        if isPaused { return }
        // Defensive: a Timer's already-fired closure can run AFTER we
        // invalidate the timer (the queued Task is past the
        // invalidation point). If that race lands inside a hold or an
        // in-flight Ask, dropping this transition is correct —
        // scheduleNextPhase will restart it once the user is done.
        if isHolding || isAnswering { return }
        switch phase {
        case .atStop:
            // If the user just finished the FINAL stop's atStop window,
            // the tour is over — transition to the terminal `complete`
            // state instead of continuing the between → approaching →
            // next-stop cycle.
            if stopIdx >= trail.stops.count - 1 {
                phase = .complete
                // Tour over — clear any lingering narration state so
                // scheduleNextPhase doesn't try to restart the cycle.
                narrationFullText = nil
                narrationDelivered = ""
                narrationPaused = false
            } else {
                phase = .between
            }
        case .between:
            phase = .approaching
        case .approaching:
            // No more wrap-around: atStop → complete handles the
            // last-stop case above. The modulo is kept as a defensive
            // guard against off-by-one bugs (it's a no-op now).
            stopIdx = (stopIdx + 1) % trail.stops.count
            phase = .atStop
            // Refresh the LM's stop framing so any Ask the user makes
            // at this new stop is grounded in the right content.
            gemma.setActiveContext(trail: trail, stopIdx: stopIdx)
            // Auto-narrate the stop's content on arrival. The lyric
            // (= what Kokoro is saying) is the only at-stop text.
            // `spokenNarrationWithPayoff` prepends the optional
            // `payoff` line (which resolves the previous stop's
            // `lookFor` prompt) so the user hears the callback first.
            // No-op for stops without a payoff — falls back to plain
            // spokenNarration.
            speakNarration(
                currentStop.spokenNarrationWithPayoff,
                preamble: "Arriving at \(currentStop.name)…"
            )
        case .complete:
            // Terminal state — nothing to advance to.
            return
        }
        scheduleNextPhase()
    }

    /// True while we have an active narration or one paused mid-flight.
    private var narrationActive: Bool {
        narrationFullText != nil || tts.isSpeaking
    }

    // MARK: - Narration: speak / interrupt / resume

    /// Begin speaking `text` through Kokoro. Records `text` so we can
    /// resume from a captured cut-off point if interrupted by a question.
    /// `preamble` is shown faintly in the lyric area during the load
    /// window before Kokoro's first audio frame arrives — keeps the
    /// screen from looking frozen at the start of the tour.
    private func speakNarration(_ text: String, preamble: String = "Setting the scene…") {
        guard !text.isEmpty else { return }
        narrationFullText = text
        narrationDelivered = ""
        narrationPaused = false
        narrationPreamble = preamble
        currentlySpeaking = .narration
        tts.synthesize(text: text, speed: 1.0)
    }

    /// User is starting to ask a question. If a narration is currently
    /// in flight — either audibly speaking, OR queued in the synth
    /// pipeline but not yet emitting audio — capture how much got
    /// delivered and halt the audio. We can't gate solely on
    /// `tts.isSpeaking` because there's a 0.5–2 s window between
    /// `tts.synthesize` being called and the first chunk producing
    /// sound; a hold landing inside that window would leave the
    /// narration synth running and silently break the answer's
    /// subsequent `tts.synthesize` (which guards on `!isRunning`).
    private func interruptNarrationForQuestion() {
        guard narrationFullText != nil else { return }
        narrationDelivered = tts.currentCaption
        narrationPaused = true
        currentlySpeaking = .none
        tts.stop()
    }

    /// After a Q&A turn finishes (Gemma + Kokoro both done), if a
    /// narration was paused, resume it from the unspoken remainder.
    /// Prepends a short bridge phrase so the user knows we're picking
    /// up where we left off, not starting over.
    private func resumeNarrationIfNeeded() {
        guard narrationPaused, let full = narrationFullText else { return }
        let remaining = remainingNarrationText(full: full, delivered: narrationDelivered)
        narrationPaused = false
        narrationDelivered = ""
        guard !remaining.isEmpty else {
            narrationFullText = nil
            return
        }
        let bridged = "Let me continue my explanation. " + remaining
        narrationFullText = remaining   // resume reference for further interrupts
        narrationPreamble = "Continuing…"
        currentlySpeaking = .narration
        tts.synthesize(text: bridged, speed: 1.0)
    }

    /// Trim a long caption so the lyric area shows the most recent
    /// content. Eviction is **sentence-based** rather than per-character:
    /// we always show the last `maxSentences` complete sentences plus
    /// any partial in-flight sentence. When a new sentence starts past
    /// that budget, the oldest sentence drops in one clean step.
    ///
    /// Why not per-character: trimming one word off the front every
    /// time a new word arrives makes the display look like it's
    /// "creeping" leftward, which is jarring. Sentence boundaries are
    /// natural pause points in the narration, so dropping a whole
    /// sentence there reads as a clean scroll.
    private func rollingCaption(_ full: String, maxSentences: Int = 3) -> String {
        guard !full.isEmpty else { return full }
        let sentences = Self.splitIntoSentences(full)
        if sentences.count <= maxSentences { return full }
        return sentences.suffix(maxSentences).joined(separator: " ")
    }

    /// Split a string at sentence-ending punctuation (`. ! ?`) followed
    /// by whitespace. Trailing partial (no terminator yet) is included
    /// as the last entry so we can show a sentence in the process of
    /// being read aloud.
    private static func splitIntoSentences(_ text: String) -> [String] {
        var sentences: [String] = []
        var current = ""
        let chars = Array(text)
        var i = 0
        while i < chars.count {
            let c = chars[i]
            current.append(c)
            if c == "." || c == "!" || c == "?",
               i + 1 < chars.count,
               chars[i + 1].isWhitespace {
                let s = current.trimmingCharacters(in: .whitespacesAndNewlines)
                if !s.isEmpty { sentences.append(s) }
                current = ""
            }
            i += 1
        }
        let tail = current.trimmingCharacters(in: .whitespacesAndNewlines)
        if !tail.isEmpty { sentences.append(tail) }
        return sentences
    }

    /// Try to find where in `full` the delivered caption left off, and
    /// return everything after it. Falls back to the full text if we
    /// can't find a clean boundary (better to re-narrate than to skip).
    private func remainingNarrationText(full: String, delivered: String) -> String {
        let trimmed = delivered.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return full }
        // Caption tokens may not match `full`'s whitespace exactly.
        // Match on the last ~30 chars of delivered to find our place.
        let needle = String(trimmed.suffix(30))
        if let r = full.range(of: needle) {
            let tail = String(full[r.upperBound...]).trimmingCharacters(in: .whitespacesAndNewlines)
            return tail
        }
        // No clean match — re-narrate from the top.
        return full
    }

    /// Watcher: when `tts.isSpeaking` flips false, decide what just
    /// finished and clean up.
    ///
    /// .narration ending naturally → clear narration state, restart phase
    /// .answer ending → runAsk's own flow handles bridge/resume; we just
    ///   reset `currentlySpeaking` here. (Don't touch narration state.)
    /// .narration was interrupted (narrationPaused) → don't clear; the
    ///   resume path will re-set .narration when Kokoro starts again.
    private func handleSpeakingFinished() {
        switch currentlySpeaking {
        case .answer:
            currentlySpeaking = .none
        case .narration:
            currentlySpeaking = .none
            if !narrationPaused, narrationFullText != nil {
                narrationFullText = nil
                narrationDelivered = ""
                scheduleNextPhase()
            }
        case .none:
            break
        }
    }

    // MARK: - Helpers

    /// Safe — never indexes into an empty `trail.stops`. Returns a
    /// neutral placeholder when the trail has no content. Render paths
    /// that touch `currentStop` are also gated behind `walkingContent`,
    /// which is only shown when stops is non-empty; this is just
    /// belt-and-braces against a future regression.
    private var currentStop: TrailStop {
        if let s = trail.stops[safe: stopIdx] { return s }
        if let first = trail.stops.first { return first }
        return Self.placeholderStop
    }
    private var nextStop: TrailStop {
        guard !trail.stops.isEmpty else { return Self.placeholderStop }
        let n = (stopIdx + 1) % trail.stops.count
        return trail.stops[safe: n] ?? currentStop
    }

    private static let placeholderStop = TrailStop(
        number: 1,
        name: "—",
        imageURL: nil,
        sentences: [],
        journalFact: ""
    )
}

// MARK: - Animation helpers

/// One-shot ripple grow + fade, looped infinitely.
private struct RippleAnim: ViewModifier {
    let delay: Double
    @State private var t: Double = 0
    func body(content: Content) -> some View {
        content
            .scaleEffect(1.0 + t * 0.9)
            .opacity(0.7 - t * 0.7)
            .onAppear {
                withAnimation(
                    .easeOut(duration: 2.0).delay(delay).repeatForever(autoreverses: false)
                ) {
                    t = 1.0
                }
            }
    }
}

/// Pulsing dot used in the listening eyebrow.
private struct BreathePulse: ViewModifier {
    @State private var on = false
    func body(content: Content) -> some View {
        content
            .scaleEffect(on ? 1.4 : 1.0)
            .opacity(on ? 0.5 : 1.0)
            .onAppear {
                withAnimation(.easeInOut(duration: 0.7).repeatForever(autoreverses: true)) {
                    on = true
                }
            }
    }
}

// MARK: - Array safe-subscript

extension Array {
    subscript(safe index: Int) -> Element? {
        indices.contains(index) ? self[index] : nil
    }
}

#Preview {
    let r = AppRouter(); r.currentTrail = TrailData.kildoo
    return WalkingView()
        .environmentObject(r)
        .environmentObject(GemmaService())
        .environmentObject(ValidationRunner())
        .environmentObject(SpeechRecognizer())
}
